[project]
name = "ai-system-for-supporting-parliamentary-petition-work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "deepagents>=0.7.13",
    "langchain-nvidia-ai-endpoints>=1.4.3",
    "langchain-openai>=1.6.2",
    "langchain-nvidia-ai-endpoints>=1.4.3",
    "langchain-qdrant>=1.1.0",
    "langgraph>=1.2.11",
    "numpy>=2.5.3",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "playwright>=1.62.0",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "sentence-transformers>=6.0.1",
    "langchain-huggingface>=1.2.2",
    "langchain-groq>=1.1.3",
]
